// Package palettegen generates internal/theme/artificer_gen.go from the
// vendored Artificer palette at internal/theme/artificer/_palette.json. It is
// importable (both cmd/main.go and internal/theme's freshness test use it)
// rather than a script, so the generator and the test that checks its output
// is current can never drift apart on how rendering works — only on whether
// it was re-run.
package palettegen

import (
	"encoding/json"
	"fmt"
	"go/format"
	"sort"
	"strings"

	"github.com/cameronsjo/forgectl/internal/theme"
)

// roleGoNames is theme.ArtificerRoleSources's Go constant name for each
// entry, in the same order — palettegen never imports the unexported role
// name list, and a generated array literal needs the exported Go identifier
// ("RoleAccent"), not the lowercase config spelling ("accent") RoleNames()
// returns.
var roleGoNames = []string{
	"RoleAccent", "RoleOK", "RoleDanger", "RoleWarn", "RoleActive", "RoleMuted", "RoleMeta", "RoleDim",
	"RoleFg", "RoleSteel", "RoleBrand", "RoleSurfaceRaised", "RoleAccentFill", "RoleOnAccent",
	"RoleUrgentFill", "RoleOnUrgent", "RoleBg",
}

// paletteFile is the shape of _palette.json this generator reads. Only the
// fields Render needs are declared — the file carries $description, $roles,
// and $notes too, which are documentation for a human editing the palette by
// hand and irrelevant to code generation.
type paletteFile struct {
	Version string            `json:"$version"`
	Dark    map[string]string `json:"dark"`
	Light   map[string]string `json:"light"`
}

// Render parses palette (the bytes of _palette.json) and emits Go source
// declaring `func Artificer() Palette`, with every role's dark and light hex
// resolved through theme.ArtificerRoleSources. The result is run through
// go/format before being returned, so a generated file never needs a
// separate gofmt pass.
//
// Render errors, rather than emitting an empty hex, when palette is missing a
// key any RoleSource needs — a silently-blank role would compile and then
// render invisible text.
func Render(palette []byte) ([]byte, error) {
	if len(roleGoNames) != len(theme.ArtificerRoleSources) {
		return nil, fmt.Errorf("palettegen: roleGoNames has %d entries, ArtificerRoleSources has %d; the two lists have drifted apart",
			len(roleGoNames), len(theme.ArtificerRoleSources))
	}

	var pf paletteFile
	if err := json.Unmarshal(palette, &pf); err != nil {
		return nil, fmt.Errorf("palettegen: parse palette JSON: %w", err)
	}
	if pf.Version == "" {
		return nil, fmt.Errorf("palettegen: palette JSON has no $version")
	}

	var entries []string
	var missing []string
	for i, src := range theme.ArtificerRoleSources {
		dark, darkOK := pf.Dark[src.PaletteKey]
		light, lightOK := pf.Light[src.PaletteKey]
		if !darkOK || dark == "" {
			missing = append(missing, fmt.Sprintf("dark.%s (role %s)", src.PaletteKey, roleGoNames[i]))
		}
		if !lightOK || light == "" {
			missing = append(missing, fmt.Sprintf("light.%s (role %s)", src.PaletteKey, roleGoNames[i]))
		}
		if darkOK && lightOK && dark != "" && light != "" {
			entries = append(entries, fmt.Sprintf("\t\t\t%s: {Dark: %q, Light: %q},", roleGoNames[i], dark, light))
		}
	}
	if len(missing) > 0 {
		sort.Strings(missing)
		return nil, fmt.Errorf("palettegen: palette JSON is missing required keys: %s", strings.Join(missing, ", "))
	}

	src := fmt.Sprintf(`// Code generated by palettegen from %s (version %s). DO NOT EDIT.

package theme

// Artificer returns the Artificer role palette, resolved from the vendored
// palette at internal/theme/%s (version %s).
func Artificer() Palette {
	return Palette{
		Name: "Artificer",
		Roles: [numRoles]Pair{
%s
		},
	}
}
`, theme.PalettePath, pf.Version, theme.PalettePath, pf.Version, strings.Join(entries, "\n"))

	formatted, err := format.Source([]byte(src))
	if err != nil {
		return nil, fmt.Errorf("palettegen: gofmt generated source: %w", err)
	}
	return formatted, nil
}
