package main

import (
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"testing"
)

func TestChangelogOwnershipGuard(t *testing.T) {
	repo := t.TempDir()
	runGit(t, repo, "init")
	runGit(t, repo, "config", "user.name", "Forgectl Test")
	runGit(t, repo, "config", "user.email", "forgectl-test@example.invalid")
	writeTestChangelog(t, repo, "# Changelog\n")
	runGit(t, repo, "add", "CHANGELOG.md")
	runGit(t, repo, "commit", "-m", "initial changelog")
	base := strings.TrimSpace(runGit(t, repo, "rev-parse", "HEAD"))

	guard, err := filepath.Abs("scripts/check-changelog-owner.sh")
	if err != nil {
		t.Fatalf("resolve changelog guard: %v", err)
	}

	if output, err := runChangelogGuard(t, repo, guard, base, "contributor", "fix/docs", "cameronsjo/forgectl"); err != nil {
		t.Fatalf("unchanged changelog rejected: %v\n%s", err, output)
	}

	writeTestChangelog(t, repo, "# Changelog\n\nGenerated release update.\n")
	runGit(t, repo, "add", "CHANGELOG.md")
	runGit(t, repo, "commit", "-m", "change changelog")

	tests := []struct {
		name       string
		base       string
		author     string
		headRef    string
		headRepo   string
		wantErr    bool
		wantOutput string
	}{
		{
			name:       "ordinary pull request is rejected",
			base:       base,
			author:     "contributor",
			headRef:    "fix/docs",
			headRepo:   "cameronsjo/forgectl",
			wantErr:    true,
			wantOutput: "CHANGELOG.md is generated by Release Please",
		},
		{
			name:     "release please pull request is allowed",
			base:     base,
			author:   "artificer-forge-bellows[bot]",
			headRef:  "release-please--branches--main",
			headRepo: "cameronsjo/forgectl",
		},
		{
			name:       "different author on the release branch is rejected",
			base:       base,
			author:     "contributor",
			headRef:    "release-please--branches--main",
			headRepo:   "cameronsjo/forgectl",
			wantErr:    true,
			wantOutput: "CHANGELOG.md is generated by Release Please",
		},
		{
			name:       "lookalike branch from a fork is rejected",
			base:       base,
			author:     "artificer-forge-bellows[bot]",
			headRef:    "release-please--branches--main",
			headRepo:   "attacker/forgectl",
			wantErr:    true,
			wantOutput: "CHANGELOG.md is generated by Release Please",
		},
		{
			name:       "different bot branch is rejected",
			base:       base,
			author:     "artificer-forge-bellows[bot]",
			headRef:    "release-please--branches--other",
			headRepo:   "cameronsjo/forgectl",
			wantErr:    true,
			wantOutput: "CHANGELOG.md is generated by Release Please",
		},
		{
			name:       "invalid base cannot be mistaken for an allowed change",
			base:       "not-a-commit",
			author:     "artificer-forge-bellows[bot]",
			headRef:    "release-please--branches--main",
			headRepo:   "cameronsjo/forgectl",
			wantErr:    true,
			wantOutput: "Unable to compare CHANGELOG.md with base commit",
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			output, err := runChangelogGuard(t, repo, guard, tt.base, tt.author, tt.headRef, tt.headRepo)
			if tt.wantErr && err == nil {
				t.Fatalf("guard unexpectedly passed\n%s", output)
			}
			if !tt.wantErr && err != nil {
				t.Fatalf("guard unexpectedly failed: %v\n%s", err, output)
			}
			if tt.wantOutput != "" && !strings.Contains(output, tt.wantOutput) {
				t.Fatalf("guard output %q does not contain %q", output, tt.wantOutput)
			}
		})
	}
}

// TestChangelogOwnershipGuardIgnoresMainsOwnReleaseEdit pins #458. In CI the
// checkout is the pull-request merge commit, which also carries any release
// that landed on main after the branch point. That release's CHANGELOG.md
// edit belongs to main, not to the PR, whichever base SHA the event reports.
func TestChangelogOwnershipGuardIgnoresMainsOwnReleaseEdit(t *testing.T) {
	repo := t.TempDir()
	runGit(t, repo, "init", "-b", "main")
	runGit(t, repo, "config", "user.name", "Forgectl Test")
	runGit(t, repo, "config", "user.email", "forgectl-test@example.invalid")
	writeTestChangelog(t, repo, "# Changelog\n")
	runGit(t, repo, "add", "CHANGELOG.md")
	runGit(t, repo, "commit", "-m", "initial changelog")
	branchPoint := strings.TrimSpace(runGit(t, repo, "rev-parse", "HEAD"))

	runGit(t, repo, "checkout", "-b", "feature")
	if err := os.WriteFile(filepath.Join(repo, "code.txt"), []byte("change\n"), 0o600); err != nil {
		t.Fatalf("write code: %v", err)
	}
	runGit(t, repo, "add", "code.txt")
	runGit(t, repo, "commit", "-m", "feature change")

	runGit(t, repo, "checkout", "main")
	writeTestChangelog(t, repo, "# Changelog\n\n## 1.0.0\n")
	runGit(t, repo, "add", "CHANGELOG.md")
	runGit(t, repo, "commit", "-m", "release")
	mainTip := strings.TrimSpace(runGit(t, repo, "rev-parse", "HEAD"))

	// Recreate refs/pull/N/merge: main's tip merged with the PR head.
	runGit(t, repo, "checkout", "--detach", mainTip)
	runGit(t, repo, "merge", "--no-ff", "-m", "merge pr", "feature")

	guard, err := filepath.Abs("scripts/check-changelog-owner.sh")
	if err != nil {
		t.Fatalf("resolve changelog guard: %v", err)
	}
	for _, base := range []string{branchPoint, mainTip} {
		if output, err := runChangelogGuard(t, repo, guard, base, "contributor", "feature", "cameronsjo/forgectl"); err != nil {
			t.Fatalf("base %s: a release on main was blamed on the PR: %v\n%s", base, err, output)
		}
	}
}

func runChangelogGuard(t *testing.T, repo, guard, base, author, headRef, headRepo string) (string, error) {
	t.Helper()
	cmd := exec.CommandContext(t.Context(), guard)
	cmd.Dir = repo
	cmd.Env = append(os.Environ(),
		"BASE_SHA="+base,
		"PR_AUTHOR="+author,
		"HEAD_REF="+headRef,
		"HEAD_REPO="+headRepo,
		"BASE_REPO=cameronsjo/forgectl",
	)
	output, err := cmd.CombinedOutput()
	return string(output), err
}

func runGit(t *testing.T, dir string, args ...string) string {
	t.Helper()
	// The arguments are fixed test fixtures, never external input.
	cmd := exec.CommandContext(t.Context(), "git", args...) //nolint:gosec
	cmd.Dir = dir
	output, err := cmd.CombinedOutput()
	if err != nil {
		t.Fatalf("git %s: %v\n%s", strings.Join(args, " "), err, output)
	}
	return string(output)
}

func writeTestChangelog(t *testing.T, repo, contents string) {
	t.Helper()
	if err := os.WriteFile(filepath.Join(repo, "CHANGELOG.md"), []byte(contents), 0o600); err != nil {
		t.Fatalf("write test changelog: %v", err)
	}
}
