package main

import (
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"testing"
)

func TestChangelogOwnershipGuard(t *testing.T) {
	repo := t.TempDir()
	runGit(t, repo, "init")
	runGit(t, repo, "config", "user.name", "Forgectl Test")
	runGit(t, repo, "config", "user.email", "forgectl-test@example.invalid")
	writeTestChangelog(t, repo, "# Changelog\n")
	runGit(t, repo, "add", "CHANGELOG.md")
	runGit(t, repo, "commit", "-m", "initial changelog")
	base := strings.TrimSpace(runGit(t, repo, "rev-parse", "HEAD"))

	guard, err := filepath.Abs("scripts/check-changelog-owner.sh")
	if err != nil {
		t.Fatalf("resolve changelog guard: %v", err)
	}

	if output, err := runChangelogGuard(repo, guard, base, "contributor", "fix/docs", "cameronsjo/forgectl"); err != nil {
		t.Fatalf("unchanged changelog rejected: %v\n%s", err, output)
	}

	writeTestChangelog(t, repo, "# Changelog\n\nGenerated release update.\n")
	runGit(t, repo, "add", "CHANGELOG.md")
	runGit(t, repo, "commit", "-m", "change changelog")

	tests := []struct {
		name       string
		base       string
		author     string
		headRef    string
		headRepo   string
		wantErr    bool
		wantOutput string
	}{
		{
			name:       "ordinary pull request is rejected",
			base:       base,
			author:     "contributor",
			headRef:    "fix/docs",
			headRepo:   "cameronsjo/forgectl",
			wantErr:    true,
			wantOutput: "CHANGELOG.md is generated by Release Please",
		},
		{
			name:     "release please pull request is allowed",
			base:     base,
			author:   "artificer-forge-bellows[bot]",
			headRef:  "release-please--branches--main",
			headRepo: "cameronsjo/forgectl",
		},
		{
			name:       "different author on the release branch is rejected",
			base:       base,
			author:     "contributor",
			headRef:    "release-please--branches--main",
			headRepo:   "cameronsjo/forgectl",
			wantErr:    true,
			wantOutput: "CHANGELOG.md is generated by Release Please",
		},
		{
			name:       "lookalike branch from a fork is rejected",
			base:       base,
			author:     "artificer-forge-bellows[bot]",
			headRef:    "release-please--branches--main",
			headRepo:   "attacker/forgectl",
			wantErr:    true,
			wantOutput: "CHANGELOG.md is generated by Release Please",
		},
		{
			name:       "different bot branch is rejected",
			base:       base,
			author:     "artificer-forge-bellows[bot]",
			headRef:    "release-please--branches--other",
			headRepo:   "cameronsjo/forgectl",
			wantErr:    true,
			wantOutput: "CHANGELOG.md is generated by Release Please",
		},
		{
			name:       "invalid base cannot be mistaken for an allowed change",
			base:       "not-a-commit",
			author:     "artificer-forge-bellows[bot]",
			headRef:    "release-please--branches--main",
			headRepo:   "cameronsjo/forgectl",
			wantErr:    true,
			wantOutput: "Unable to compare CHANGELOG.md with base commit",
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			output, err := runChangelogGuard(repo, guard, tt.base, tt.author, tt.headRef, tt.headRepo)
			if tt.wantErr && err == nil {
				t.Fatalf("guard unexpectedly passed\n%s", output)
			}
			if !tt.wantErr && err != nil {
				t.Fatalf("guard unexpectedly failed: %v\n%s", err, output)
			}
			if tt.wantOutput != "" && !strings.Contains(output, tt.wantOutput) {
				t.Fatalf("guard output %q does not contain %q", output, tt.wantOutput)
			}
		})
	}
}

func runChangelogGuard(repo, guard, base, author, headRef, headRepo string) (string, error) {
	cmd := exec.Command(guard)
	cmd.Dir = repo
	cmd.Env = append(os.Environ(),
		"BASE_SHA="+base,
		"PR_AUTHOR="+author,
		"HEAD_REF="+headRef,
		"HEAD_REPO="+headRepo,
		"BASE_REPO=cameronsjo/forgectl",
	)
	output, err := cmd.CombinedOutput()
	return string(output), err
}

func runGit(t *testing.T, dir string, args ...string) string {
	t.Helper()
	cmd := exec.Command("git", args...)
	cmd.Dir = dir
	output, err := cmd.CombinedOutput()
	if err != nil {
		t.Fatalf("git %s: %v\n%s", strings.Join(args, " "), err, output)
	}
	return string(output)
}

func writeTestChangelog(t *testing.T, repo, contents string) {
	t.Helper()
	if err := os.WriteFile(filepath.Join(repo, "CHANGELOG.md"), []byte(contents), 0o644); err != nil {
		t.Fatalf("write test changelog: %v", err)
	}
}
