package main

import (
	"bytes"
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"testing"

	"gopkg.in/yaml.v3"
)

// updatePlansIndex rewrites docs/plans/README.md from the plans' frontmatter
// instead of failing on drift: go test -run TestPlansIndex -update .
var updatePlansIndex = flag.Bool("update", false, "rewrite docs/plans/README.md from the plans' status frontmatter")

// planStatuses is the closed status vocabulary, in the order the index
// lists its sections. It deliberately has no "deprecated": the key is also
// OKF's trust key (internal/docs/trust.go), where an exact "deprecated"
// makes `forgectl docs check` fail, so a superseded plan says "superseded".
var planStatuses = []struct{ status, heading, blurb string }{
	{"current", "Current", "Forward-looking and in force until a later one supersedes it."},
	{"in-flight", "In flight", "Being built now."},
	{"proposed", "Proposed", "Written, not started."},
	{"done", "Done", "Built. Read as history, not as a spec: the shipped behavior and its ADR are the current truth."},
	{"superseded", "Superseded", "Replaced by a later plan, which the file names at its top."},
}

type planEntry struct{ file, title, status string }

func readPlan(t *testing.T, dir, name string) planEntry {
	t.Helper()
	raw, err := os.ReadFile(filepath.Clean(filepath.Join(dir, name)))
	if err != nil {
		t.Fatalf("read %s: %v", name, err)
	}
	body := raw
	var status string
	if rest, ok := bytes.CutPrefix(raw, []byte("---\n")); ok {
		block, after, found := bytes.Cut(rest, []byte("\n---\n"))
		if found {
			var fm struct {
				Status string `yaml:"status"`
			}
			if err := yaml.Unmarshal(block, &fm); err != nil {
				t.Fatalf("%s: frontmatter is not valid YAML: %v", name, err)
			}
			status, body = fm.Status, after
		}
	}
	var title string
	for _, line := range strings.Split(string(body), "\n") {
		if h, ok := strings.CutPrefix(line, "# "); ok {
			title = strings.TrimSpace(h)
			break
		}
	}
	if title == "" {
		t.Errorf("%s: no top-level heading to use as the index title", name)
	}
	return planEntry{file: name, title: title, status: status}
}

func renderPlansIndex(entries []planEntry) string {
	var b strings.Builder
	b.WriteString("# Plans\n\n")
	b.WriteString("<!-- Generated by TestPlansIndex (docs_plans_index_test.go). Do not edit by hand:\n")
	b.WriteString("     set `status:` in a plan's frontmatter, then run `go test -run TestPlansIndex -update .` -->\n\n")
	b.WriteString("Every plan carries a `status:` in its frontmatter, one of ")
	for i, s := range planStatuses {
		if i > 0 {
			b.WriteString(", ")
		}
		fmt.Fprintf(&b, "`%s`", s.status)
	}
	b.WriteString(". This page is generated from them.\n")
	for _, s := range planStatuses {
		var rows []planEntry
		for _, e := range entries {
			if e.status == s.status {
				rows = append(rows, e)
			}
		}
		if len(rows) == 0 {
			continue
		}
		fmt.Fprintf(&b, "\n## %s\n\n%s\n\n", s.heading, s.blurb)
		for _, e := range rows {
			fmt.Fprintf(&b, "- [%s](%s)\n", strings.ReplaceAll(e.title, "|", `\|`), e.file)
		}
	}
	return b.String()
}

// TestPlansIndex fails when a plan has a missing or out-of-set status, or
// when docs/plans/README.md differs from what the plans' frontmatter
// generates. -update rewrites the README.
func TestPlansIndex(t *testing.T) {
	dir := filepath.Join("docs", "plans")
	files, err := filepath.Glob(filepath.Join(dir, "*.md"))
	if err != nil {
		t.Fatal(err)
	}
	sort.Strings(files)
	valid := map[string]bool{}
	for _, s := range planStatuses {
		valid[s.status] = true
	}
	var entries []planEntry
	for _, f := range files {
		name := filepath.Base(f)
		if name == "README.md" {
			continue
		}
		e := readPlan(t, dir, name)
		switch {
		case e.status == "":
			t.Errorf("%s: missing frontmatter status: (one of current, in-flight, proposed, done, superseded)", name)
		case !valid[e.status]:
			t.Errorf("%s: status %q is outside the closed set (current, in-flight, proposed, done, superseded); \"deprecated\" is never valid, it is OKF's trust state", name, e.status)
		}
		entries = append(entries, e)
	}
	if len(entries) == 0 {
		t.Fatal("no plans found under docs/plans")
	}
	if t.Failed() {
		return
	}
	want := renderPlansIndex(entries)
	readme := filepath.Join(dir, "README.md")
	if *updatePlansIndex {
		if err := os.WriteFile(readme, []byte(want), 0o600); err != nil {
			t.Fatal(err)
		}
		return
	}
	got, err := os.ReadFile(filepath.Clean(readme))
	if err != nil {
		t.Fatalf("%v; generate it with: go test -run TestPlansIndex -update .", err)
	}
	if string(got) != want {
		t.Errorf("docs/plans/README.md is stale; regenerate with: go test -run TestPlansIndex -update .")
	}
}
