// Code generated by palettegen from artificer/_palette.json (version 0.25.0). DO NOT EDIT.

package theme

// Artificer returns the Artificer role palette, resolved from the vendored
// palette at internal/theme/artificer/_palette.json (version 0.25.0).
func Artificer() Palette {
	return Palette{
		Name: "Artificer",
		Roles: [numRoles]Pair{
			RoleAccent:        {Dark: "#dbbb6f", Light: "#7a5a10"},
			RoleOK:            {Dark: "#4a8a5e", Light: "#2a5a3a"},
			RoleDanger:        {Dark: "#e6a8a2", Light: "#8a2418"},
			RoleWarn:          {Dark: "#c4808a", Light: "#8a6618"},
			RoleActive:        {Dark: "#c4808a", Light: "#8a6618"},
			RoleMuted:         {Dark: "#5a7a8a", Light: "#5a7a8a"},
			RoleMeta:          {Dark: "#c5c8c6", Light: "#4a3f2a"},
			RoleDim:           {Dark: "#666666", Light: "#8a8070"},
			RoleFg:            {Dark: "#e8e6e1", Light: "#20203e"},
			RoleSteel:         {Dark: "#b8cad4", Light: "#2e4a5a"},
			RoleBrand:         {Dark: "#b095e0", Light: "#5a35b0"},
			RoleSurfaceRaised: {Dark: "#313540", Light: "#eddcc0"},
			RoleAccentFill:    {Dark: "#c4932a", Light: "#c4932a"},
			RoleOnAccent:      {Dark: "#20203e", Light: "#20203e"},
			RoleUrgentFill:    {Dark: "#a04540", Light: "#8a2418"},
			RoleOnUrgent:      {Dark: "#f5ead0", Light: "#f5ead0"},
			RoleBg:            {Dark: "#292c33", Light: "#f5ead0"},
		},
	}
}
