#!/bin/sh

set -eu

: "${BASE_SHA:?BASE_SHA must be set}"
: "${PR_AUTHOR:?PR_AUTHOR must be set}"
: "${HEAD_REF:?HEAD_REF must be set}"
: "${HEAD_REPO:?HEAD_REPO must be set}"
: "${BASE_REPO:?BASE_REPO must be set}"

set +e
git diff --quiet "$BASE_SHA" HEAD -- CHANGELOG.md
diff_status=$?
set -e

case "$diff_status" in
	0)
		exit 0
		;;
	1)
		;;
	*)
		echo "::error::Unable to compare CHANGELOG.md with base commit $BASE_SHA." >&2
		exit "$diff_status"
		;;
esac

if [ "$PR_AUTHOR" = 'artificer-forge-bellows[bot]' ] &&
	[ "$HEAD_REF" = 'release-please--branches--main' ] &&
	[ "$HEAD_REPO" = "$BASE_REPO" ]; then
	exit 0
fi

echo "::error::CHANGELOG.md is generated by Release Please; add release prose to the pull-request body commit override described in AGENTS.md." >&2
exit 1
