package redact

import (
	"strings"
	"testing"
)

// textOnMain pairs each corpus input with what Text printed for it at
// 5d13a16, the main commit before #983. The corpus is the stdoutKept,
// stdoutWithheld and stdoutExempt rows, a PEM block, and the YAML
// value-on-the-next-line cases. The second column is frozen: it is what the
// earlier Text did, not what this one should, so a row added later takes its
// value from that commit's Text, never from the current one.
var textOnMain = []struct{ in, main string }{
	{"Package" + strings.Repeat(" ", 20) + "Current   Wanted   Latest  Location" + strings.Repeat(" ", 32) + "Depended by", "Package" + strings.Repeat(" ", 20) + "Current   Wanted   Latest  Location" + strings.Repeat(" ", 32) + "Depended by"},
	{"@anthropic-ai/claude-code   2.1.42  2.1.286  2.1.286  node_modules/@anthropic-ai/claude-code  global", "[redacted]"},
	{"@openai/codex" + strings.Repeat(" ", 16) + "0.1.0    0.2.0    0.2.0  node_modules/@openai/codex" + strings.Repeat(" ", 14) + "global", "[redacted]"},
	{"npm" + strings.Repeat(" ", 25) + "10.8.2   10.9.0   11.0.0  node_modules/npm" + strings.Repeat(" ", 24) + "global", "npm" + strings.Repeat(" ", 25) + "10.8.2   10.9.0   11.0.0  node_modules/npm" + strings.Repeat(" ", 24) + "global"},
	{"npm warn deprecated inflight@1.0.6: This module is not supported, and leaks memory.", "[redacted]"},
	{"npm_config_prefix=/usr/local", "npm_config_prefix=/usr/local"},
	{"python@3.12 (3.12.1) < 3.12.2", "[redacted]"},
	{"openssl@3 (3.3.1) < 3.3.2", "[redacted]"},
	{"==> Updating Homebrew...", "==> Updating Homebrew..."},
	{"Updated 2 taps (homebrew/core and homebrew/cask).", "Updated 2 taps (homebrew/core and homebrew/cask)."},
	{"Updated https://github.com/Homebrew/brew from 1a2b3c4 to 5d6e7f8.", "Updated https://github.com/Homebrew/brew from 1a2b3c4 to 5d6e7f8."},
	{"==> Upgrading python@3.12 3.12.1 -> 3.12.2", "[redacted]"},
	{"==> Pouring python@3.12--3.12.2.arm64_sonoma.bottle.tar.gz", "[redacted]"},
	{"🍺  /opt/homebrew/Cellar/python@3.12/3.12.2: 3,300 files, 65MB", "[redacted]"},
	{"==> Downloading https://ghcr.io/v2/homebrew/core/python/3.12/blobs/sha256:4f2a9c0e", "[redacted]"},
	{"Removing: /Users/me/Library/Caches/Homebrew/node@20--20.1.0.tar.gz... (12MB)", "[redacted]"},
	{"forgectl 0.22.0 -> 0.23.0", "forgectl 0.22.0 -> 0.23.0"},
	{"Already up-to-date.", "Already up-to-date."},
	{"From https://github.com/o/r", "From https://github.com/o/r"},
	{" * branch" + strings.Repeat(" ", 12) + "main       -> FETCH_HEAD", " * branch" + strings.Repeat(" ", 12) + "main       -> FETCH_HEAD"},
	{"Updating 1a2b3c4..5d6e7f8", "Updating 1a2b3c4..5d6e7f8"},
	{"Fast-forward", "Fast-forward"},
	{" README.md | 2 +-", " README.md | 2 +-"},
	{"Cloning into 'r'... from git@github.com:o/r.git.", "Cloning into 'r'... from git@github.com:o/r.git."},
	{"remote: ssh://git@github.com/o/r.git", "remote: ssh://git@github.com/o/r.git"},
	{"try main@{u} instead", "try main@{u} instead"},
	{"  ✓ Logged in to github.com account octocat (keyring)", "  ✓ Logged in to github.com account octocat (keyring)"},
	{"  - Token scopes: 'gist', 'read:org', 'repo'", "  - Token scopes: 'gist', 'read:org', 'repo'"},
	{"go version go1.26.0 darwin/arm64", "go version go1.26.0 darwin/arm64"},
	{"go: downloading golang.org/x/tools v0.30.0", "go: downloading golang.org/x/tools v0.30.0"},
	{"ghp_short", "ghp_short"},
	{"sk-12345", "sk-12345"},
	{"task-1234567890abcdefghijklmnop", "task-1234567890abcdefghijklmnop"},
	{"AKIAshort", "AKIAshort"},
	{"Bearer token", "[redacted]"},
	{"GITHUB_TOKEN=", "[redacted]"},
	{"error validating token: expired", "error validating token: expired"},
	{"Contact support@example.com for help", "[redacted]"},
	{"-----BEGIN CERTIFICATE-----", "-----BEGIN CERTIFICATE-----"},
	{"[redacted]", "[redacted]"},
	{"", ""},
	{"\"token\": \"\",", "\"token\": \"\","},
	{"\"password\": null", "\"password\": null"},
	{"  \"credentials\": {", "  \"credentials\": {"},
	{"password:", "password:"},
	{"  token: |", "  token: |"},
	{"api_key: ~", "api_key: ~"},
	{"\"tokens\": []", "\"tokens\": []"},
	{"Downloading http://registry.local:4873/@scope/pkg/-/pkg-1.0.0.tgz", "[redacted]"},
	{"GET https://registry.npmjs.org/@anthropic-ai%2fclaude-code 200", "[redacted]"},
	{"eyJhbGciOiJIUzI1NiJ9", "eyJhbGciOiJIUzI1NiJ9"},
	{"eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxIn0", "eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxIn0"},
	{"eyJ.abcd.efgh", "eyJ.abcd.efgh"},
	{"glcbt-short", "glcbt-short"},
	{"pass the token with --token", "[redacted]"},
	{"\x1b[32m==>\x1b[0m \x1b[1mUpgrading 1 outdated package:\x1b[0m", "\x1b[32m==>\x1b[0m \x1b[1mUpgrading 1 outdated package:\x1b[0m"},
	{"basic authentication disabled", "[redacted]"},
	{"bearer authentication is not configured", "[redacted]"},
	{"pass=1 fail=0 skip=2", "[redacted]"},
	{"auth=ok", "[redacted]"},
	{"Cookie: none", "[redacted]"},
	{"> Cookie: none", "[redacted]"},
	{"  auth: true", "[redacted]"},
	{"  \"auth\": \"ok\",", "[redacted]"},
	{" src/token=x.go | 1 +", "[redacted]"},
	{" src/password=reset.go | 12 ++++++------", "[redacted]"},
	{" assets/token=logo.png | Bin 0 -> 1234 bytes", "[redacted]"},
	{" docs/password=reset.md | 3 ++-", "[redacted]"},
	{"PASS=3 FAIL=0", "[redacted]"},
	{"password = \"\"", "password = \"\""},
	{"token := \"\"", "token := \"\""},
	{"token == x", "token == x"},
	{"token: expired", "[redacted]"},
	{"password: required", "[redacted]"},
	{"auth: required", "[redacted]"},
	{"token_expiry: 3600", "[redacted]"},
	{"\"token_type\": \"bearer\"", "[redacted]"},
	{"password_policy: strict", "[redacted]"},
	{"tokenType: bearer", "[redacted]"},
	{"Signature: valid", "[redacted]"},
	{"credential.helper: osxkeychain", "[redacted]"},
	{"credentials: ~/.aws/credentials", "[redacted]"},
	{"use --token to pass it", "[redacted]"},
	{"docker.io/library/node:22@sha256:0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f", "[redacted]"},
	{"Digest: sha256:0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f", "Digest: sha256:0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f"},
	{"Status: Downloaded newer image for node:22", "Status: Downloaded newer image for node:22"},
	{"remote: https://x-access-token:SEKRIT@github.com/o/r", "[redacted]"},
	{"https://SEKRIT@github.com/o/r", "[redacted]"},
	{"fatal: unable to access 'http:///U:SEKRIT@host/r/': URL rejected", "[redacted]"},
	{"http:/U:SEKRIT@host/r", "[redacted]"},
	{"https:////SEKRIT@host/r", "[redacted]"},
	{"http::http://U:SEKRIT@host/r", "[redacted]"},
	{"user:SEKRIT@host", "[redacted]"},
	{"ssh://gitx:SEKRIT@host/o/r", "[redacted]"},
	{"ssh://SEKRIT@host/o/r", "[redacted]"},
	{"proxy=http://u:SEKRIT@proxy:3128", "[redacted]"},
	{"Authorization: token SEKRIT", "[redacted]"},
	{"> proxy-authorization: Basic SEKRIT", "[redacted]"},
	{"remote: Private-Token: SEKRIT", "[redacted]"},
	{"X-Api-Key: SEKRIT", "[redacted]"},
	{"Cookie: session=SEKRIT", "[redacted]"},
	{"< Set-Cookie: sid=SEKRIT; Path=/", "[redacted]"},
	{"curl -H 'Bearer SEKRIT12'", "[redacted]"},
	{"Basic dXNlcjpTRUtSSVQ=", "[redacted]"},
	{"token ghp_" + strings.Repeat("A1", 18), "[redacted]"},
	{"gho_" + strings.Repeat("b", 36), "[redacted]"},
	{"(ghu_" + strings.Repeat("C", 36) + ")", "[redacted]"},
	{"ghs_" + strings.Repeat("d", 36), "[redacted]"},
	{"ghr_" + strings.Repeat("e", 36), "[redacted]"},
	{"github_pat_11ABCDEFG0123456789_abcdefghij", "[redacted]"},
	{"glpat-" + strings.Repeat("x", 20), "[redacted]"},
	{"glptt-" + strings.Repeat("0", 40), "[redacted]"},
	{"key: sk-" + strings.Repeat("Z", 48), "[redacted]"},
	{"sk-ant-api03-" + strings.Repeat("q", 40), "[redacted]"},
	{"sk-proj-" + strings.Repeat("r", 40), "[redacted]"},
	{"sk_live_" + strings.Repeat("s", 24), "[redacted]"},
	{"xoxb-123456789012-abcdef", "[redacted]"},
	{"AKIAIOSFODNN7EXAMPLE", "[redacted]"},
	{"id=ASIAIOSFODNN7EXAMPLE", "[redacted]"},
	{"npm_" + strings.Repeat("t", 36), "[redacted]"},
	{"AIza" + strings.Repeat("u", 35), "[redacted]"},
	{"hf_" + strings.Repeat("v", 34), "[redacted]"},
	{"pypi-" + strings.Repeat("w", 60), "[redacted]"},
	{"shpat_" + strings.Repeat("a", 32), "[redacted]"},
	{"GITHUB_TOKEN=SEKRIT", "[redacted]"},
	{"export NPM_AUTH=SEKRIT", "[redacted]"},
	{"--password=SEKRIT", "[redacted]"},
	{"HOMEBREW_GITHUB_API_TOKEN=SEKRIT", "[redacted]"},
	{"\"token\": \"SEKRIT\"", "[redacted]"},
	{"{\"access_token\":\"SEKRIT\",\"token_type\":\"bearer\"}", "[redacted]"},
	{"  \"password\" : \"SEKRIT\",", "[redacted]"},
	{"{\"client_secret\": 12345678}", "[redacted]"},
	{"password: SEKRIT", "[redacted]"},
	{"  - api_key: SEKRIT", "[redacted]"},
	{"'secret': SEKRIT", "[redacted]"},
	{"  - Token: gho_" + strings.Repeat("*", 36), "[redacted]"},
	{"X-Auth-Token: SEKRIT", "[redacted]"},
	{"< x-github-token: SEKRIT", "[redacted]"},
	{"--password SEKRIT", "[redacted]"},
	{"gh auth login --with-token SEKRIT", "[redacted]"},
	{"eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJTRUtSSVQifQ.c2lnbmF0dXJl", "[redacted]"},
	{"id_token=eyJhbGciOiJub25lIn0.eyJhIjoxfQ.", "[redacted]"},
	{"glcbt-64_" + strings.Repeat("x", 20), "[redacted]"},
	{"glcbt-" + strings.Repeat("y", 20), "[redacted]"},
	{"fatal: unable to access 'http://user:pa/SEKRIT@127.0.0.1:9/r/': URL rejected: Port number was not a decimal number between 0 and 65535", "[redacted]"},
	{"http://user:pa?SEKRIT@host/r", "[redacted]"},
	{"https://user:pa#SEKRIT@host/r", "[redacted]"},
	{"https://user:/SEKRIT@host/r", "[redacted]"},
	{"ghp_" + strings.Repeat("A", 18) + "\x1b[0m" + strings.Repeat("A", 18), "[redacted]"},
	{"\x1b[1mAuthorization\x1b[0m: SEKRIT", "[redacted]"},
	{"GITHUB_TOKEN=\x1b[31m", "[redacted]"},
	{"Basic authentication disabled", "[redacted]"},
	{"Bearer authentication", "[redacted]"},
	{"basic dXNlcjpTRUtSSVQ=", "[redacted]"},
	{"bearer abc123defghij", "[redacted]"},
	{"PASSWORD=ok horse battery", "[redacted]"},
	{"pass=1234", "[redacted]"},
	{"Cookie: none; sid=SEKRIT", "[redacted]"},
	{"> Cookie: none; sid=SEKRIT", "[redacted]"},
	{"> Cookie: none SEKRIT", "[redacted]"},
	{"\"auth\": \"ok SEKRIT\"", "[redacted]"},
	{"auth: ok SEKRIT", "[redacted]"},
	{" src/app.go | 1 + GITHUB_TOKEN=SEKRIT", "[redacted]"},
	{"GITHUB_TOKEN=SEKRIT src/app.go | 1 +", "[redacted]"},
	{"PASSWORD=hunter2 | 3", "[redacted]"},
	{" GITHUB_TOKEN=abc | 1 +", "[redacted]"},
	{" src/GITHUB_TOKEN=abc/x.go | 1 +", "[redacted]"},
	{" src/GITHUB_TOKEN=SEKRIT | 2 +-", "[redacted]"},
	{"basic dXNlcjpwYXNz", "[redacted]"},
	{"bearer abcdefghijklmnop", "[redacted]"},
	{"BEARER abcdefghij", "[redacted]"},
	{"BASIC abcdefghijkl", "[redacted]"},
	{"password=123", "[redacted]"},
	{"pass=1", "[redacted]"},
	{"pass=12 skip=0", "[redacted]"},
	{"DB_PASS=12 fail=0", "[redacted]"},
	{"\"auth\": 1", "[redacted]"},
	{"auth: 1", "[redacted]"},
	{"{'token': 'abc'}", "{'token': 'abc'}"},
	{"{'password': 'SEKRIT', 'user': 'me'}", "{'password': 'SEKRIT', 'user': 'me'}"},
	{"password = \"x\"", "password = \"x\""},
	{"token = 'abcdef'", "token = 'abcdef'"},
	{"  api_key = \"SEKRIT\"", "  api_key = \"SEKRIT\""},
	{"\"token\" = \"SEKRIT\"", "\"token\" = \"SEKRIT\""},
	{"token := \"abc\"", "token := \"abc\""},
	{"\tsecret := SEKRIT", "\tsecret := SEKRIT"},
	{"ghp_" + strings.Repeat("A", 18) + "\x1b]8;;\x1b\\" + strings.Repeat("A", 18), "ghp_" + strings.Repeat("A", 18) + "\x1b]8;;\x1b\\" + strings.Repeat("A", 18)},
	{"ghp_" + strings.Repeat("A", 18) + "\x1b]8;;https://example.com\a" + strings.Repeat("A", 18), "[redacted]"},
	{"token: expired SEKRIT", "[redacted]"},
	{"token_type_secret: SEKRIT", "[redacted]"},
	{"credentials: /SEKRIT/x", "[redacted]"},
	{"credentials: ~/x SEKRIT", "[redacted]"},
	{"use --token SEKRIT", "[redacted]"},
	{"user:SEKRIT@sha256:abc", "[redacted]"},
	{"https://u:SEKRIT@host/x@sha256:0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f", "[redacted]"},
	{"key:\n-----BEGIN PRIVATE KEY-----\nMIIEowIBAAKCAQEA" + strings.Repeat("b", 48) + "\n-----END PRIVATE KEY-----\nafter", "key:\n[redacted]\n[redacted]\n[redacted]\nafter"},
	{"password: |\n  SEKRIT\n  more\nother: 1", "password: |\n  SEKRIT\n  more\nother: 1"},
	{"password: >-\n    SEKRIT\nnext", "password: >-\n    SEKRIT\nnext"},
	{"password:\n  SEKRIT\nother: x", "password:\n  SEKRIT\nother: x"},
	{"  token:\n    SEKRIT\n  other: x", "  token:\n    SEKRIT\n  other: x"},
	{"password:\n- SEKRIT\n- two\nnext", "password:\n- SEKRIT\n- two\nnext"},
	{"- password:\n  SEKRIT\n- other", "- password:\n  SEKRIT\n- other"},
	{"password: |\n  SEKRIT\n\n  more\nx", "password: |\n  SEKRIT\n\n  more\nx"},
	{"\x1b[1mpassword\x1b[0m:\n  SEKRIT", "\x1b[1mpassword\x1b[0m:\n  SEKRIT"},
	{"password:\nnext: 1", "password:\nnext: 1"},
	{"password: x\n  SEKRIT", "[redacted]\n  SEKRIT"},
	{"token_type:\n  bearer", "token_type:\n[redacted]"},
	{"token: |\n  ghp_" + strings.Repeat("A1", 18) + "\n  b", "token: |\n[redacted]\n  b"}}

// TestText_NeverWeakerThanMain: #983 tightens Text and narrows only Stdout,
// so every line the earlier Text withheld on the corpus (textOnMain) is
// still withheld, and Stdout still withholds nothing Text keeps.
//
// Mutations that turn it red: make Text's pemScan deliverable (the basic,
// bearer, pass=1 fail=0 and key-status rows come through Text); drop the
// deliverable guard in keyNameCarries (token_type rows come through Text).
func TestText_NeverWeakerThanMain(t *testing.T) {
	for _, c := range textOnMain {
		in, was, now := strings.Split(c.in, "\n"), strings.Split(c.main, "\n"), strings.Split(Text(c.in), "\n")
		if len(was) != len(in) || len(now) != len(in) {
			t.Fatalf("line count changed on %q: main %d, now %d, input %d", c.in, len(was), len(now), len(in))
		}
		for i := range in {
			if was[i] == Marker && in[i] != Marker && now[i] != Marker {
				t.Errorf("Text keeps line %d of %q, which it withheld before #983: %q", i, c.in, now[i])
			}
		}
		checkStdoutWithinText(t, c.in)
	}
}
