package surface_test

import (
	"errors"
	"strings"
	"testing"

	"github.com/cameronsjo/forgectl/internal/surface"
)

// TestNewNonce_IsFullWidthAndDistinct pins the two properties. The distinctness
// loop is what would catch a constructor that forgot to draw entropy and
// returned a constant — which every other test here would pass over.
func TestNewNonce_IsFullWidthAndDistinct(t *testing.T) {
	seen := make(map[string]bool, 64)
	for range 64 {
		n, err := surface.NewNonce()
		if err != nil {
			t.Fatalf("NewNonce: %v", err)
		}
		if !n.Valid() {
			t.Fatal("a fresh nonce is not valid")
		}
		s := n.String()
		if len(s) != 64 {
			t.Fatalf("nonce encodes to %d characters, want 64", len(s))
		}
		if seen[s] {
			t.Fatalf("NewNonce repeated %q; it is not drawing entropy", s)
		}
		seen[s] = true
	}
}

// TestNonce_RoundTripsThroughItsEncoding covers the path the nonce actually
// takes: generated by the outer process, rendered into a bootstrap command a
// manager types, parsed back out of a hello frame.
func TestNonce_RoundTripsThroughItsEncoding(t *testing.T) {
	original, err := surface.NewNonce()
	if err != nil {
		t.Fatalf("NewNonce: %v", err)
	}

	parsed, err := surface.ParseNonce(original.String())
	if err != nil {
		t.Fatalf("ParseNonce: %v", err)
	}
	if !original.Equal(parsed) {
		t.Error("a nonce did not survive its own encoding")
	}

	// And a different nonce must not compare equal, or the assertion above
	// would pass over a comparison that always returns true.
	other, err := surface.NewNonce()
	if err != nil {
		t.Fatalf("NewNonce: %v", err)
	}
	if original.Equal(other) {
		t.Error("two independently drawn nonces compared equal")
	}
}

// TestParseNonce_GrammarIsExact keeps the comparison honest. Two spellings of
// one nonce is one more than a constant-time comparison can be written
// against, so uppercase hex is refused rather than folded.
func TestParseNonce_GrammarIsExact(t *testing.T) {
	valid := strings.Repeat("ab", 32)

	refused := map[string]string{
		"empty":            "",
		"too short":        valid[:63],
		"too long":         valid + "a",
		"uppercase":        strings.ToUpper(valid),
		"non-hex":          strings.Repeat("z", 64),
		"leading space":    " " + valid[1:],
		"embedded newline": valid[:32] + "\n" + valid[33:],
	}

	for name, in := range refused {
		t.Run(name, func(t *testing.T) {
			n, err := surface.ParseNonce(in)
			if !errors.Is(err, surface.ErrInvalidNonce) {
				t.Errorf("ParseNonce(%q) err = %v, want ErrInvalidNonce", in, err)
			}
			if n.Valid() {
				t.Error("a refused nonce reports itself valid")
			}
		})
	}

	// The control: the well-formed value parses, so the refusals above are the
	// grammar discriminating rather than ParseNonce refusing everything.
	if _, err := surface.ParseNonce(valid); err != nil {
		t.Errorf("ParseNonce refused a well-formed nonce: %v", err)
	}
}

// TestNonce_ZeroValueMatchesNothing is the property a fail-closed handshake
// depends on. Two unset nonces comparing equal would mean a peer that sent
// nothing authenticating against a service that generated nothing.
func TestNonce_ZeroValueMatchesNothing(t *testing.T) {
	var zero surface.Nonce
	if zero.Valid() {
		t.Error("the zero nonce reports itself valid")
	}
	if zero.Equal(zero) {
		t.Error("two unset nonces compared equal")
	}

	drawn, err := surface.NewNonce()
	if err != nil {
		t.Fatalf("NewNonce: %v", err)
	}
	if drawn.Equal(zero) || zero.Equal(drawn) {
		t.Error("a real nonce compared equal to an unset one")
	}
}

// TestNonce_EqualIsLengthSafe covers the case a byte-at-a-time comparison
// would get wrong or panic on: operands of different widths.
func TestNonce_EqualIsLengthSafe(t *testing.T) {
	full, err := surface.ParseNonce(strings.Repeat("ab", 32))
	if err != nil {
		t.Fatalf("ParseNonce: %v", err)
	}

	// A prefix-matching nonce must not compare equal. This is the shape a
	// timing attack would be walking toward one byte at a time.
	near, err := surface.ParseNonce(strings.Repeat("ab", 31) + "ac")
	if err != nil {
		t.Fatalf("ParseNonce: %v", err)
	}
	if full.Equal(near) {
		t.Error("nonces differing only in the last byte compared equal")
	}

	var empty surface.Nonce
	if full.Equal(empty) {
		t.Error("a full nonce compared equal to a zero-width one")
	}
}
